$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\street\powerpole"
$modelname "scenery/street/powerpole/powerpole.mdl"
$cdmaterials "models/scenery/street/powerpole/"
$surfaceprop ""
$model "Body" "powerpole.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -48.3339 -10.191302 -201.0403 49.3492 9.527202 239.9315
$sequence "idle" "powerpole_@idle" activity "" 1.0 fps 5.0

