$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\street\powerpole"
$modelname "scenery/street/powerpole/powerpolesky.mdl"
$cdmaterials "models/scenery/street/powerpole/"
$surfaceprop "wood"
$model "Body" "powerpolesky.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -3.0209 -0.63700014 -12.565 3.0843 0.5955001 14.9957
$sequence "idle" "powerpolesky_@idle" activity "" 1.0 fps 1.0

