$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\furniture\coffeetable1"
$modelname "scenery/furniture/coffeetable1/chanttbl2.mdl"
$cdmaterials "models/scenery/furniture/coffeetable1/"
$surfaceprop ""
$model "Body" "chanttbl2.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -35.1731 -16.325401 -14.5761 35.1731 16.325401 14.5761
$sequence "only_sequence" "chanttbl2_@only_sequence" activity "ACT_IDLE" 1.0 fps 30.0

