$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\furniture\coffeetable1"
$modelname "scenery/furniture/CoffeeTable1/CoffeeTable1.mdl"
$cdmaterials "models/scenery/furniture/CoffeeTable1/"
$surfaceprop ""
$model "Body" "CoffeeTable1_r.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -37.67949 -22.832071 0.0 37.67949 22.832071 23.93152
$sequence "only_sequence" "coffeetable1_@only_sequence" activity "ACT_IDLE" 1.0 fps 30.0

