$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\furniture\coffeetable1"
$modelname "scenery/furniture/coffeetable1/vestbl.mdl"
$cdmaterials "models/scenery/furniture/coffeetable1/"
$surfaceprop ""
$model "Body" "vestbl.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -15.5407 -11.051101 -17.9111 15.614401 10.219201 17.9628
$sequence "only_sequence" "vestbl_@only_sequence" activity "ACT_IDLE" 1.0 fps 30.0

