$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\furniture\chair_executive"
$modelname "scenery/furniture/chair_executive/chair_executive.mdl"
$cdmaterials "models/scenery/furniture/chair_executive/"
$surfaceprop ""
$model "Body" "newchair_r.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -18.15138 -15.53506 0.0 11.2078 15.53506 47.45196
$sequence "idle" "chair_executive_@idle" activity "ACT_IDLE" 1.0 fps 30.0

