$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\furniture\chair_executive"
$modelname "scenery/furniture/chair_executive/chair_executive_ruin.mdl"
$cdmaterials "models/scenery/furniture/chair_executive/"
$surfaceprop ""
$model "Body" "chair_executive_ruin_r.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -19.9583 -18.1634 0.0 14.6746 18.1902 54.9328
$sequence "idle" "chair_executive_ruin_@idle" activity "ACT_IDLE" 1.0 fps 30.0

