$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\furniture\heartbed"
$modelname "scenery/furniture/HeartBed/HeartBed.mdl"
$cdmaterials "models/scenery/furniture/HeartBed/"
$surfaceprop "rubber"
$model "Body" "HeartBed_REF.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -88.7796 -81.0027 -29.0047 90.1868 81.5799 31.22
$sequence "idle" "heartbed_@idle" activity "ACT_IDLE" 1.0 fps 30.0

