$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\structural\doorknoba"
$modelname "scenery/structural/doorknoba/doorknoba.mdl"
$cdmaterials "models/scenery/structural/doorknoba/"
$surfaceprop "metalpanel"
$model "Body" "doorknoba.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -2.3096 -1.8475001 -2.3723 2.316 1.8435 2.3723
$sequence "idle" "doorknoba_@idle" activity "" 1.0 fps 1.0

