$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\furniture\papasan"
$modelname "scenery/furniture/Papasan/Papasan.mdl"
$cdmaterials "models/scenery/furniture/Papasan/"
$surfaceprop "wood"
$model "Body" "Papasan_REF.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -29.5447 -33.141 -25.3128 30.0548 32.4621 24.3402
$sequence "idle" "papasan_@idle" activity "ACT_IDLE" 1.0 fps 30.0

