$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\furniture\beda"
$modelname "scenery/furniture/beda/bedashort.mdl"
$cdmaterials "models/scenery/furniture/beda/"
$surfaceprop ""
$model "Body" "bedashort.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -50.9719 -35.958 -31.1717 49.7249 35.958004 31.1717
$sequence "idle" "bedashort_@idle" activity "act_idle" 1.0 fps 30.0

