$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\furniture\vanity"
$modelname "scenery/furniture/Vanity/Vanity.mdl"
$cdmaterials "models/scenery/furniture/Vanity/"
$surfaceprop "wood"
$model "Body" "Vanity_REF.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -11.957502 -39.3345 -41.1514 11.9646015 39.5789 41.1417
$sequence "idle" "vanity_@idle" activity "ACT_IDLE" 1.0 fps 30.0

