$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\structural\vesuvius"
$modelname "scenery/structural/vesuvius/atm_Useable.mdl"
$cdmaterials "models/scenery/structural/vesuvius/"
$surfaceprop "plastic"
$model "Body" "atm_Useable_REF.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -7.5736995 -12.936 -34.4799 7.5734005 12.9433 34.2512
$sequence "idle" "atm_useable_@idle" activity "" 1.0 fps 1.0

