$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\structural\vesuvius"
$modelname "scenery/structural/vesuvius/bar.mdl"
$cdmaterials "models/scenery/structural/vesuvius/"
$surfaceprop "glass"
$model "Body" "bar.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -7.442798 -46.1553 -5.4626 7.542401 41.3187 61.8911
$sequence "only_sequence" "bar_@only_sequence" activity "ACT_IDLE" 1.0 fps 30.0

