$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\structural\vesuvius"
$modelname "scenery/structural/vesuvius/bartap.mdl"
$cdmaterials "models/scenery/structural/vesuvius/"
$surfaceprop "metal"
$model "Body" "bartap.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -6.791101 -18.1292 -9.8266 6.791101 18.1292 9.8266
$sequence "idle" "bartap_@idle" activity "" 1.0 fps 1.0

