$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\structural\vesuvius"
$modelname "scenery/structural/vesuvius/boothcorner.mdl"
$cdmaterials "models/scenery/structural/vesuvius/"
$surfaceprop "rubber"
$model "Body" "boothcorner.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -17.7452 -17.7452 -14.4406 17.7452 17.7452 14.4406
$sequence "idle" "boothcorner_@idle" activity "" 1.0 fps 1.0

