$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\structural\vesuvius"
$modelname "scenery/structural/vesuvius/booth.mdl"
$cdmaterials "models/scenery/structural/vesuvius/"
$surfaceprop "rubber"
$model "Body" "booth.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -17.568502 -45.5303 -14.4406 17.568502 45.5303 14.4406
$sequence "idle" "booth_@idle" activity "" 1.0 fps 1.0

