$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\structural\vesuvius"
$modelname "scenery/structural/vesuvius/boothleft.mdl"
$cdmaterials "models/scenery/structural/vesuvius/"
$surfaceprop "rubber"
$model "Body" "boothleft.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -17.5 -18.3673 -14.459 18.3603 17.493 14.459
$sequence "idle" "boothleft_@idle" activity "" 1.0 fps 1.0

