$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\structural\vesuvius"
$modelname "scenery/structural/vesuvius/chair.mdl"
$cdmaterials "models/scenery/structural/vesuvius/"
$surfaceprop "rubber"
$model "Body" "chair.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -28.2276 -31.9297 -21.9015 14.887001 31.9297 23.4553
$sequence "idle" "chair_@idle" activity "" 1.0 fps 1.0

