$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\structural\vesuvius"
$modelname "scenery/structural/vesuvius/curtain.mdl"
$cdmaterials "models/scenery/structural/vesuvius/"
$surfaceprop ""
$model "Body" "curtain.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -4.6076016 -34.3365 -58.8173 4.607599 34.3365 58.8173
$sequence "idle" "curtain_@idle" activity "" 1.0 fps 1.0

