$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\structural\vesuvius"
$modelname "scenery/structural/vesuvius/display.mdl"
$cdmaterials "models/scenery/structural/vesuvius/"
$surfaceprop "plastic"
$model "Body" "display.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -13.677902 -41.4772 -22.9508 13.677899 41.4772 43.0813
$sequence "idle" "display_@idle" activity "" 1.0 fps 1.0

