$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\structural\vesuvius"
$modelname "scenery/structural/vesuvius/fridge.mdl"
$cdmaterials "models/scenery/structural/vesuvius/"
$surfaceprop ""
$model "Body" "fridge.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -13.615803 -55.7945 -109.2387 13.615803 55.7945 3.1742
$sequence "only_sequence" "fridge_@only_sequence" activity "ACT_IDLE" 1.0 fps 30.0

