$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\structural\vesuvius"
$modelname "scenery/structural/vesuvius/glass_rack.mdl"
$cdmaterials "models/scenery/structural/vesuvius/"
$surfaceprop "glass"
$model "Body" "glass_rack.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -12.777201 -30.6159 -12.7742 12.777201 30.6159 12.7742
$sequence "idle" "glass_rack_@idle" activity "" 1.0 fps 1.0

