$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\structural\vesuvius"
$modelname "scenery/structural/vesuvius/marquee.mdl"
$cdmaterials "models/scenery/structural/vesuvius/"
$surfaceprop "plastic"
$model "Body" "marquee.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -2.9820023 -51.5 -20.0194 2.9820023 51.5 20.0194
$sequence "idle" "marquee_@idle" activity "" 1.0 fps 1.0

