$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\structural\vesuvius"
$modelname "scenery/structural/vesuvius/pole.mdl"
$cdmaterials "models/scenery/structural/vesuvius/"
$surfaceprop "metal"
$model "Body" "pole.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -3.5732 -3.6283 -43.3158 3.5732 3.6283 65.8673
$sequence "idle" "pole_@idle" activity "" 1.0 fps 1.0

