$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\structural\vesuvius"
$modelname "scenery/structural/vesuvius/sign.mdl"
$cdmaterials "models/scenery/structural/vesuvius/"
$surfaceprop "metalpanel"
$model "Body" "sign.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -17.280005 -65.2432 -133.828 17.280003 70.0491 128.9606
$sequence "idle" "sign_@idle" activity "" 1.0 fps 1.0

