$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\structural\vesuvius"
$modelname "scenery/structural/vesuvius/signb.mdl"
$cdmaterials "models/scenery/structural/vesuvius/"
$surfaceprop "plastic"
$model "Body" "signb.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -9.751702 -57.293 -22.3969 9.7517 57.293 22.3969
$sequence "idle" "signb_@idle" activity "" 1.0 fps 1.0

