$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\structural\vesuvius"
$modelname "scenery/structural/vesuvius/sofa.mdl"
$cdmaterials "models/scenery/structural/vesuvius/"
$surfaceprop "rubber"
$model "Body" "sofa.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -28.227602 -68.8763 -23.4553 28.227602 68.8763 23.4553
$sequence "idle" "sofa_@idle" activity "" 1.0 fps 1.0

