$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\structural\vesuvius"
$modelname "scenery/structural/vesuvius/stage_top.mdl"
$cdmaterials "models/scenery/structural/vesuvius/"
$surfaceprop "plaster"
$model "Body" "stage_top.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -160.5 -111.5 -50.172 160.5 111.5 50.172
$sequence "only_sequence" "stage_top_@only_sequence" activity "ACT_IDLE" 1.0 fps 30.0

