$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\structural\vesuvius"
$modelname "scenery/structural/vesuvius/stage_bottom.mdl"
$cdmaterials "models/scenery/structural/vesuvius/"
$surfaceprop "plaster"
$model "Body" "stage_bottom.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -152.685 -105.5353 -21.4556 152.685 105.5353 21.4556
$sequence "only_sequence" "stage_bottom_@only_sequence" activity "ACT_IDLE" 1.0 fps 30.0

