$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\structural\vesuvius"
$modelname "scenery/structural/vesuvius/stalactitec.mdl"
$cdmaterials "models/scenery/structural/vesuvius/"
$surfaceprop "plaster"
$model "Body" "stalactitec.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -35.0 -38.5 -40.9561 35.0 38.5 40.9561
$sequence "only_sequence" "stalactitec_@only_sequence" activity "ACT_IDLE" 1.0 fps 30.0

