$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\structural\vesuvius"
$modelname "scenery/structural/vesuvius/stalactited.mdl"
$cdmaterials "models/scenery/structural/vesuvius/"
$surfaceprop "plaster"
$model "Body" "stalactited.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -26.0 -25.5 -26.0629 26.0 25.5 26.0629
$sequence "only_sequence" "stalactited_@only_sequence" activity "ACT_IDLE" 1.0 fps 30.0

