$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\structural\vesuvius"
$modelname "scenery/structural/vesuvius/stalactiteb.mdl"
$cdmaterials "models/scenery/structural/vesuvius/"
$surfaceprop "plaster"
$model "Body" "stalactiteb.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -48.0 -49.0 -63.2957 48.0 49.0 63.2957
$sequence "only_sequence" "stalactiteb_@only_sequence" activity "ACT_IDLE" 1.0 fps 30.0

