$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\structural\vesuvius"
$modelname "scenery/structural/vesuvius/stalactitea.mdl"
$cdmaterials "models/scenery/structural/vesuvius/"
$surfaceprop "plaster"
$model "Body" "stalactitea.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -55.5 -55.0 -22.3397 55.5 55.0 22.3397
$sequence "only_sequence" "stalactitea_@only_sequence" activity "ACT_IDLE" 1.0 fps 30.0

