$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\structural\vesuvius"
$modelname "scenery/structural/vesuvius/stalactite_all.mdl"
$cdmaterials "models/scenery/structural/vesuvius/"
$surfaceprop ""
$model "Body" "stalactite_all.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -279.5 -322.0 -63.2957 279.5 322.0 63.2957
$sequence "only_sequence" "stalactite_all_@only_sequence" activity "ACT_IDLE" 1.0 fps 30.0

