$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\structural\vesuvius"
$modelname "scenery/structural/vesuvius/table_lamp.mdl"
$cdmaterials "models/scenery/structural/vesuvius/"
$surfaceprop "glass"
$model "Body" "table_lamp.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -12.8361 -12.8361 -14.8444 12.8361 12.8361 14.8444
$sequence "idle" "table_lamp_@idle" activity "" 1.0 fps 1.0

