$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\structural\vesuvius"
$modelname "scenery/structural/vesuvius/vip.mdl"
$cdmaterials "models/scenery/structural/vesuvius/"
$surfaceprop "metal"
$model "Body" "vip.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -2.0033935E-4 -22.5743 -70.3838 8.985 22.5743 11.264
$sequence "idle" "vip_@idle" activity "" 1.0 fps 1.0

