$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\structural\vesuvius"
$modelname "scenery/structural/vesuvius/windowblock.mdl"
$cdmaterials "models/scenery/structural/vesuvius/"
$surfaceprop ""
$model "Body" "windowblock.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -1.1868104 0.0 0.0 0.0155 236.2756 66.5872
$sequence "idle" "windowblock_@idle" activity "" 1.0 fps 1.0

