$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\furniture\ascandleb"
$modelname "scenery/furniture/ascandleb/ascandleb.mdl"
$cdmaterials "models/scenery/furniture/ascandleb/"
$surfaceprop ""
$model "Body" "ascandleb.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -1.4331 -1.4644 -0.9852 1.4153 1.4574 1.6493
$sequence "idle" "ascandleb_@idle" activity "" 1.0 fps 5.0

