$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\furniture\couchbackless"
$modelname "scenery/furniture/CouchBackless/CouchBackless.mdl"
$cdmaterials "models/scenery/furniture/CouchBackless/"
$surfaceprop "rubber"
$model "Body" "CouchBackless_REF.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -20.144398 -62.994 -16.9163 19.852198 62.588 15.9617
$sequence "idle" "couchbackless_@idle" activity "ACT_IDLE" 1.0 fps 30.0

