$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\furniture\diningroom_chairs"
$modelname "scenery/furniture/Diningroom_Chairs/Diningroom_Chairs.mdl"
$cdmaterials "models/scenery/furniture/Diningroom_Chairs/"
$surfaceprop ""
$model "Body" "Diningroom_Chairs_r.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -12.5196 -14.016021 0.0 12.392531 13.955679 45.55841
$sequence "idle" "diningroom_chairs_@idle" activity "ACT_IDLE" 1.0 fps 30.0

