$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\models\character\monster\gargoyle\gargoyle_gibbs"
$modelname "character/monster/gargoyle/gargoyle_gibbs/gargoyle_head.mdl"
$cdmaterials "models/character/monster/gargoyle/"
$surfaceprop "gargoyle"
$model "Body" "gargoyle_head.smd"{
}
$hboxset "default"
$hbox 0 "gargoyle_head	" -10.183743 -11.693325 -11.536217 10.183757 10.604576 12.4498825
$sequence "idle" "gargoyle_head_@idle" activity "ACT_IDLE" 1.0 fps 30.0

