$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\models\character\monster\gargoyle\gargoyle_gibbs"
$modelname "character/monster/gargoyle/gargoyle_gibbs/gargoyle_L_foot.mdl"
$cdmaterials "models/character/monster/gargoyle/"
$surfaceprop "gargoyle"
$model "Body" "gargoyle_L_foot.smd"{
}
$hboxset "default"
$hbox 0 "gargoyle_L_foot" -8.151917 -20.818275 -19.278276 8.151882 20.818325 19.278225
$sequence "idle" "gargoyle_l_foot_@idle" activity "ACT_IDLE" 1.0 fps 30.0

