$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\models\character\monster\gargoyle\gargoyle_gibbs"
$modelname "character/monster/gargoyle/gargoyle_gibbs/gargoyle_R_hand.mdl"
$cdmaterials "models/character/monster/gargoyle/"
$surfaceprop "gargoyle"
$model "Body" "gargoyle_R_hand.smd"{
}
$hboxset "default"
$hbox 0 "gargoyle_R_hand" -8.203577 -11.996452 -13.807201 8.203623 11.996548 13.807198
$sequence "idle" "gargoyle_r_hand_@idle" activity "ACT_IDLE" 1.0 fps 30.0

