$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\models\character\monster\gargoyle\gargoyle_gibbs"
$modelname "character/monster/gargoyle/gargoyle_gibbs/garg_gibbs.mdl"
$cdmaterials "models/character/monster/gargoyle/gargoyle_gibbs/"
$surfaceprop "gargoyle"
$model "Body" "garg_gibbs.smd"{
}
$hboxset "default"
$hbox 0 "chunk01" -1.4468001 -1.9493998 -1.1702003 1.3156999 1.8249002 0.9524005
$sequence "idle" "garg_gibbs_@idle" activity "ACT_IDLE" 1.0 fps 30.0

