$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\models\character\monster\gargoyle\gargoyle_gibbs"
$modelname "character/monster/gargoyle/gargoyle_gibbs/gargoyle_R_foot.mdl"
$cdmaterials "models/character/monster/gargoyle/"
$surfaceprop "gargoyle"
$model "Body" "gargoyle_R_foot.smd"{
}
$hboxset "default"
$hbox 0 "gargoyle_R_foot" -6.0909357 -14.423679 -14.855005 6.090964 7.847622 8.928595
$sequence "idle" "gargoyle_r_foot_@idle" activity "ACT_IDLE" 1.0 fps 30.0

