$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\models\character\monster\gargoyle\gargoyle_gibbs"
$modelname "character/monster/gargoyle/gargoyle_gibbs/gargoyle_L_hand.mdl"
$cdmaterials "models/character/monster/gargoyle/"
$surfaceprop "gargoyle"
$model "Body" "gargoyle_L_hand.smd"{
}
$hboxset "default"
$hbox 0 "gargoyle_L_hand" -7.196863 -11.134056 -11.726204 7.1968384 11.134043 11.726196
$sequence "idle" "gargoyle_l_hand_@idle" activity "ACT_IDLE" 1.0 fps 30.0

