$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\models\character\monster\gargoyle\gargoyle_gibbs"
$modelname "character/monster/gargoyle/gargoyle_gibbs/gargoyle_R_torso.mdl"
$cdmaterials "models/character/monster/gargoyle/"
$surfaceprop "gargoyle"
$model "Body" "gargoyle_R_torso.smd"{
}
$hboxset "default"
$hbox 0 "gargoyle_R_torso" -17.637276 -16.767952 -15.493465 17.637224 16.767948 15.493538
$sequence "idle" "gargoyle_r_torso_@idle" activity "ACT_IDLE" 1.0 fps 30.0

