$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\models\character\monster\gargoyle\gargoyle_gibbs"
$modelname "character/monster/gargoyle/gargoyle_gibbs/gargoyle_L_torso.mdl"
$cdmaterials "models/character/monster/gargoyle/"
$surfaceprop "gargoyle"
$model "Body" "gargoyle_L_torso.smd"{
}
$hboxset "default"
$hbox 0 "gargoyle_L_torso" -14.465941 -15.5607605 -15.557816 14.465958 15.5607395 15.557785
$sequence "idle" "gargoyle_l_torso_@idle" activity "ACT_IDLE" 1.0 fps 30.0

