$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\models\character\monster\gargoyle\gargoyle_gibbs"
$modelname "character/monster/gargoyle/gargoyle_gibbs/gargoyle_pelvis.mdl"
$cdmaterials "models/character/monster/gargoyle/"
$surfaceprop "gargoyle"
$model "Body" "gargoyle_pelvis.smd"{
}
$hboxset "default"
$hbox 0 "gargoyle_pelvis" -17.98174 -22.71378 -21.428358 17.981758 22.713722 21.42834
$sequence "idle" "gargoyle_pelvis_@idle" activity "ACT_IDLE" 1.0 fps 30.0

