$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\furniture\divider"
$modelname "scenery/furniture/Divider/Divider.mdl"
$cdmaterials "models/scenery/furniture/Divider/"
$surfaceprop "wood"
$model "Body" "Divider_REF.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -5.168801 -35.5622 -38.7304 5.4353013 35.2225 37.9247
$sequence "idle" "divider_@idle" activity "ACT_IDLE" 1.0 fps 30.0

