$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\furniture\clockdesktop"
$modelname "scenery/furniture/ClockDesktop/ClockDesktop.mdl"
$cdmaterials "models/scenery/furniture/ClockDesktop/"
$surfaceprop "metal"
$model "Body" "ClockDesktop_REF.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -1.7460003 -6.8111 -3.1627 1.7464001 6.7756 3.1093
$sequence "idle" "clockdesktop_@idle" activity "ACT_IDLE" 1.0 fps 30.0

