$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\furniture\chair_newage"
$modelname "scenery/furniture/chair_newage/chair.mdl"
$cdmaterials "models/scenery/furniture/chair_newage/"
$surfaceprop ""
$model "Body" "chair_r.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -13.5413 -13.5985 0.0 13.5413 13.5985 52.514
$sequence "idle" "chair_@idle" activity "ACT_IDLE" 1.0 fps 30.0

