$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\furniture\desk_executive"
$modelname "scenery/furniture/desk_executive/desk_executive_nodrawer.mdl"
$cdmaterials "models/scenery/furniture/desk_executive/"
$surfaceprop ""
$model "Body" "desk_executive_nodrawer_r.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -26.485703 -54.5692 -0.0092 24.273901 55.9074 42.6067
$sequence "idle" "desk_executive_nodrawer_@idle" activity "ACT_IDLE" 1.0 fps 30.0

