$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\furniture\desk_executive"
$modelname "scenery/furniture/desk_executive/desk_executive.mdl"
$cdmaterials "models/scenery/furniture/desk_executive/"
$surfaceprop ""
$model "Body" "desk_executive_r.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -21.904802 -44.6246 -0.0131 19.701403 45.9301 34.9179
$sequence "idle" "desk_executive_@idle" activity "ACT_IDLE" 1.0 fps 30.0

