$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\furniture\chinacabinet"
$modelname "scenery/furniture/ChinaCabinet/ChinaCabinet.mdl"
$cdmaterials "models/scenery/furniture/ChinaCabinet/"
$surfaceprop "wood"
$model "Body" "ChinaCabinet_REF.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -14.310701 -21.8327 -52.795 14.3557005 21.9141 53.3026
$sequence "idle" "chinacabinet_@idle" activity "ACT_IDLE" 1.0 fps 30.0

