$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\furniture\bookend"
$modelname "scenery/furniture/BookEnd/BookEnd.mdl"
$cdmaterials "models/scenery/furniture/BookEnd//"
$surfaceprop "Rock"
$model "Body" "BookEnd_REF.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -1.8948001 -3.1629 -5.2005 1.9085001 3.1761 5.2366
$sequence "idle" "bookend_@idle" activity "ACT_IDLE" 1.0 fps 30.0

