$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\misc\poster"
$modelname "scenery/misc/poster/poster1.mdl"
$cdmaterials "models/scenery/misc/posters/"
$surfaceprop ""
$model "Body" "poster1_r.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -1.3595203 -9.47702 -13.65479 0.0 9.47702 13.65479
$sequence "only_sequence" "poster1_@only_sequence" activity "ACT_IDLE" 1.0 fps 30.0

