$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\misc\poster"
$modelname "scenery/misc/poster/poster4.mdl"
$cdmaterials "models/scenery/misc/posters/"
$surfaceprop ""
$model "Body" "poster4_r.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -1.1212703 -8.09745 -10.79661 0.0 8.09745 10.79661
$sequence "only_sequence" "poster4_@only_sequence" activity "ACT_IDLE" 1.0 fps 30.0

