$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\misc\poster"
$modelname "scenery/misc/poster/poster1a.mdl"
$cdmaterials "models/scenery/misc/posters/"
$surfaceprop ""
$model "Body" "poster1a_r.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -1.8212906 -12.69637 -18.29332 0.0 12.69637 18.29332
$sequence "only_sequence" "poster1a_@only_sequence" activity "ACT_IDLE" 1.0 fps 30.0

