$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\misc\poster"
$modelname "scenery/misc/poster/poster_jeanette.mdl"
$cdmaterials "models/scenery/misc/posters/"
$surfaceprop ""
$model "Body" "poster_jeanette_ref.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -1.8213006 -12.6964 0.0 0.0 12.6964 47.6512
$sequence "only_sequence" "poster_jeanette_@only_sequence" activity "ACT_IDLE" 1.0 fps 30.0

