$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\misc\poster"
$modelname "scenery/misc/poster/posters6.mdl"
$cdmaterials "models/scenery/misc/posters/"
$surfaceprop ""
$model "Body" "posters6_r.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -1.5245193 -16.63561 -22.18082 0.0 16.63561 22.18082
$sequence "only_sequence" "posters6_@only_sequence" activity "ACT_IDLE" 1.0 fps 30.0

