$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\misc\poster"
$modelname "scenery/misc/poster/poster_tawni.mdl"
$cdmaterials "models/scenery/misc/posters/"
$surfaceprop ""
$model "Body" "poster_tawni_r.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -2.8425994 -17.2975 0.0 1.1155001 17.3145 47.1254
$sequence "only_sequence" "poster_tawni_@only_sequence" activity "ACT_IDLE" 1.0 fps 30.0

