$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\misc\poster"
$modelname "scenery/misc/poster/poster2a.mdl"
$cdmaterials "models/scenery/misc/posters/"
$surfaceprop ""
$model "Body" "poster2a_r.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -1.1305994 -12.33642 -16.44856 0.0 12.33642 16.44856
$sequence "only_sequence" "poster2a_@only_sequence" activity "ACT_IDLE" 1.0 fps 30.0

