$cd "C:\Users\HYPERPC\Desktop\Source 2\VTMB\SDKContent\VpkContent\decompiled_models\scenery\misc\poster"
$modelname "scenery/misc/poster/poster5.mdl"
$cdmaterials "models/scenery/misc/posters/"
$surfaceprop ""
$model "Body" "poster5_r.smd"{
}
$hboxset "default"
$hbox 0 "static_prop" -1.0222496 -11.15485 -14.87314 0.0 11.15485 14.87314
$sequence "only_sequence" "poster5_@only_sequence" activity "ACT_IDLE" 1.0 fps 30.0

